CREATE TABLE IF NOT EXISTS cartas_porte (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company_id INTEGER NOT NULL,
  numero TEXT NOT NULL,
  fecha_emision TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'Borrador',
  idioma TEXT NOT NULL DEFAULT 'es',
  tipo_servicio TEXT,
  tipo_transporte TEXT,
  lugar_emision TEXT,
  observaciones TEXT,
  condiciones_transporte TEXT,
  instrucciones_especiales TEXT,
  created_by INTEGER,
  updated_by INTEGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  remitente_nombre TEXT,
  remitente_nit TEXT,
  remitente_direccion TEXT,
  remitente_telefono TEXT,
  remitente_email TEXT,
  remitente_contacto TEXT,
  destinatario_nombre TEXT,
  destinatario_nit TEXT,
  destinatario_direccion TEXT,
  destinatario_telefono TEXT,
  destinatario_email TEXT,
  destinatario_contacto TEXT,
  transportista_nombre TEXT,
  transportista_nit TEXT,
  transportista_direccion TEXT,
  transportista_telefono TEXT,
  transportista_email TEXT,
  conductor_nombre TEXT,
  conductor_dpi TEXT,
  conductor_licencia TEXT,
  placa_vehiculo TEXT,
  marca_vehiculo TEXT,
  tipo_vehiculo TEXT,
  placa_remolque TEXT,
  numero_contenedor TEXT,
  numero_marchamo TEXT,
  origen_direccion TEXT,
  origen_municipio TEXT,
  origen_departamento TEXT,
  origen_pais TEXT,
  destino_direccion TEXT,
  destino_municipio TEXT,
  destino_departamento TEXT,
  destino_pais TEXT,
  fecha_recoleccion TEXT,
  hora_recoleccion TEXT,
  fecha_entrega_estimada TEXT,
  hora_entrega_estimada TEXT,
  total_bultos REAL NOT NULL DEFAULT 0,
  total_peso_bruto REAL NOT NULL DEFAULT 0,
  total_peso_neto REAL NOT NULL DEFAULT 0,
  total_volumen REAL NOT NULL DEFAULT 0,
  total_valor_declarado REAL NOT NULL DEFAULT 0,
  fecha_hora_recepcion TEXT,
  recibe_nombre TEXT,
  recibe_dpi TEXT,
  UNIQUE(company_id, numero)
);

CREATE TABLE IF NOT EXISTS cartas_porte_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  carta_porte_id INTEGER NOT NULL,
  cantidad_bultos REAL,
  tipo_embalaje TEXT,
  descripcion_mercancia TEXT,
  peso_bruto REAL,
  peso_neto REAL,
  volumen REAL,
  valor_declarado REAL,
  moneda TEXT,
  marcas_numeros TEXT,
  hs_code TEXT,
  observaciones TEXT,
  FOREIGN KEY (carta_porte_id) REFERENCES cartas_porte(id)
);

CREATE INDEX IF NOT EXISTS idx_cartas_porte_company_estado ON cartas_porte (company_id, estado);
CREATE INDEX IF NOT EXISTS idx_cartas_porte_company_fecha ON cartas_porte (company_id, fecha_emision);
CREATE INDEX IF NOT EXISTS idx_cartas_porte_company_numero ON cartas_porte (company_id, numero);
CREATE INDEX IF NOT EXISTS idx_cartas_porte_items_carta ON cartas_porte_items (carta_porte_id);
